<?php

namespace SyntaxSociety\PurchaseCreated;

require_once('Model.php');

class Product extends \Model {
	function getFieldSpecifications(): array {
		return [
			'id' =>            'string',
			'productUuid' =>   'string',
			'variantUuid' =>   'string',
			'description' =>   'string',
			'name' =>          'string',
			'variantName' =>   'string',
			'unitPrice' =>     'int',
			'costPrice' =>     'int',
			'quantity' =>      'string',
			'vatPercentage' => 'double',
			'autoGenerated' => 'bool',
			'type' =>          'string',
		];
	}
}
